SELECT S.STUDENT_ID,S.STUDENT_NAME,SB.SUBJECT_NAME,COUNT(E.STUDENT_ID) AS attended_exams
FROM STUDENTS S
CROSS JOIN SUBJECTS SB
LEFT JOIN EXAMINATIONS E
ON S.student_id =E.student_id 
AND SB.subject_name = E.subject_name 
GROUP BY S.STUDENT_ID, S.STUDENT_NAME, SB.SUBJECT_NAME
ORDER BY S.STUDENT_ID,SB.SUBJECT_NAME

