SELECT ROUND(COUNT(T.CUSTOMER_ID) * 100.00 / 
    (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM DELIVERY), 2) AS IMMEDIATE_PERCENTAGE
FROM (
    SELECT *,
           DENSE_RANK() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS R
    FROM DELIVERY
) AS T
WHERE R = 1 
  AND ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE;
